version: '3.8'

services:
  postgres:
    image: postgres
    container_name: montrack
    env_file:
      -.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
